package database

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// DB wraps the sqlc Queries and the connection pool
type DB struct {
	*Queries
	Pool *pgxpool.Pool
}

// NewDatabase initializes the pgxpool and returns a wrapped sqlc DB struct
func NewDatabase(connString string) (*DB, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// 1. Parse configuration
	config, err := pgxpool.ParseConfig(connString)
	if err != nil {
		return nil, fmt.Errorf("unable to parse connection string: %w", err)
	}

	// 2. Tweak pool settings (optional but recommended)
	config.MaxConns = 10
	config.MinConns = 2
	config.MaxConnIdleTime = 5 * time.Minute

	// 3. Establish connection
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		return nil, fmt.Errorf("unable to create connection pool: %w", err)
	}

	// 4. Ping to ensure connectivity
	if err := pool.Ping(ctx); err != nil {
		return nil, fmt.Errorf("unable to ping database: %w", err)
	}

	return &DB{
		Queries: New(pool), // New is generated by sqlc
		Pool:    pool,
	}, nil
}

// Close wraps the pool's close method
func (db *DB) Close() {
	db.Pool.Close()
}
